spring:
  jpa:
    show-sql: true # Muestra las sentencias SQL que Hibernate utiliza para consultar la BDD por consola
    hibernate:
      ddl-auto: none # Previene que Hibernate intente crear la estructura de la BDD basandose en las anotaciones de los modelos
  sql:
    init:
      schema-locations: classpath*:database/schema.sql
      data-locations: classpath*:database/migrations.sql
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/trello # El servicio espera que haya una BDD MySQL llamada "trello" funcionando en localhost:3006
    username: # usuario ccreado en la BDD con acceso para consultar, actualizar y crear tablas en "trello"
    password: # la contraseña para el usuario
    driverClassName: com.mysql.cj.jdbc.Driver # El driver de conexion para utilizar
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b # Clave utilizada por JSW para generar los tokens, no cambiar
    expiration-time: 3600000 #1h en milisegundos, eso es lo que dura cada token JWT.
    refresh-expiration-time: 86400000 #1 dia en milisegundos, eso es el tiempo que se puede refrescar un token.
