spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update  
  sql:
    init:
      mode: never       
  datasource:
    url: jdbc:mysql://localhost:3306/trello?useUnicode=true&characterEncoding=utf8&serverTimezone=Europe/Madrid&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ""         
    driver-class-name: com.mysql.cj.jdbc.Driver
